spring:
  application:
    name: administration-server-application

---
spring:
  config:
    activate:
      on-profile: "!kubernetes"
    import:
      - optional:configserver:http://localhost:1000/configuration
  cloud:
    config:
      enabled: true
      fail-fast: true
      name: ${spring.application.name}
      uri: http://localhost:1000/configuration

---
spring:
  config:
    activate:
      on-profile: kubernetes
  cloud:
    config:
      enabled: false